# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseBalance(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Balance']] = 'Balance'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BalanceActions[_PrismaModelT]':
        from .client import get_client

        return actions.BalanceActions[_PrismaModelT](client or get_client(), cls)


class BaseTransaction(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Transaction']] = 'Transaction'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TransactionActions[_PrismaModelT]':
        from .client import get_client

        return actions.TransactionActions[_PrismaModelT](client or get_client(), cls)


class BaseDeposit(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Deposit']] = 'Deposit'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DepositActions[_PrismaModelT]':
        from .client import get_client

        return actions.DepositActions[_PrismaModelT](client or get_client(), cls)


class BaseWithdrawal(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Withdrawal']] = 'Withdrawal'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.WithdrawalActions[_PrismaModelT]':
        from .client import get_client

        return actions.WithdrawalActions[_PrismaModelT](client or get_client(), cls)


class BaseCryptoOrder(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CryptoOrder']] = 'CryptoOrder'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CryptoOrderActions[_PrismaModelT]':
        from .client import get_client

        return actions.CryptoOrderActions[_PrismaModelT](client or get_client(), cls)


class BaseSetting(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Setting']] = 'Setting'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SettingActions[_PrismaModelT]':
        from .client import get_client

        return actions.SettingActions[_PrismaModelT](client or get_client(), cls)


class BaseCoinSetting(_PrismaModel):
    __prisma_model__: ClassVar[Literal['CoinSetting']] = 'CoinSetting'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.CoinSettingActions[_PrismaModelT]':
        from .client import get_client

        return actions.CoinSettingActions[_PrismaModelT](client or get_client(), cls)


class BasePaymentMethod(_PrismaModel):
    __prisma_model__: ClassVar[Literal['PaymentMethod']] = 'PaymentMethod'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PaymentMethodActions[_PrismaModelT]':
        from .client import get_client

        return actions.PaymentMethodActions[_PrismaModelT](client or get_client(), cls)


class BaseAdmin(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Admin']] = 'Admin'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AdminActions[_PrismaModelT]':
        from .client import get_client

        return actions.AdminActions[_PrismaModelT](client or get_client(), cls)


class BaseReferralSetting(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ReferralSetting']] = 'ReferralSetting'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ReferralSettingActions[_PrismaModelT]':
        from .client import get_client

        return actions.ReferralSettingActions[_PrismaModelT](client or get_client(), cls)


