# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('/home/runner/workspace/prisma/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'debian-openssl-3.0.x': '/home/runner/.npm/_npx/55ad0b431757dc30/node_modules/prisma/query-engine-debian-openssl-3.0.x'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    user: 'actions.UserActions[models.User]'
    balance: 'actions.BalanceActions[models.Balance]'
    transaction: 'actions.TransactionActions[models.Transaction]'
    deposit: 'actions.DepositActions[models.Deposit]'
    withdrawal: 'actions.WithdrawalActions[models.Withdrawal]'
    cryptoorder: 'actions.CryptoOrderActions[models.CryptoOrder]'
    setting: 'actions.SettingActions[models.Setting]'
    coinsetting: 'actions.CoinSettingActions[models.CoinSetting]'
    paymentmethod: 'actions.PaymentMethodActions[models.PaymentMethod]'
    admin: 'actions.AdminActions[models.Admin]'
    referralsetting: 'actions.ReferralSettingActions[models.ReferralSetting]'

    __slots__ = (
        'user',
        'balance',
        'transaction',
        'deposit',
        'withdrawal',
        'cryptoorder',
        'setting',
        'coinsetting',
        'paymentmethod',
        'admin',
        'referralsetting',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.user = actions.UserActions[models.User](self, models.User)
        self.balance = actions.BalanceActions[models.Balance](self, models.Balance)
        self.transaction = actions.TransactionActions[models.Transaction](self, models.Transaction)
        self.deposit = actions.DepositActions[models.Deposit](self, models.Deposit)
        self.withdrawal = actions.WithdrawalActions[models.Withdrawal](self, models.Withdrawal)
        self.cryptoorder = actions.CryptoOrderActions[models.CryptoOrder](self, models.CryptoOrder)
        self.setting = actions.SettingActions[models.Setting](self, models.Setting)
        self.coinsetting = actions.CoinSettingActions[models.CoinSetting](self, models.CoinSetting)
        self.paymentmethod = actions.PaymentMethodActions[models.PaymentMethod](self, models.PaymentMethod)
        self.admin = actions.AdminActions[models.Admin](self, models.Admin)
        self.referralsetting = actions.ReferralSettingActions[models.ReferralSetting](self, models.ReferralSetting)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'BOT_DATABASE'}).resolve(),
            'source_file_path': '/home/runner/workspace/prisma/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    user: 'UserBatchActions'
    balance: 'BalanceBatchActions'
    transaction: 'TransactionBatchActions'
    deposit: 'DepositBatchActions'
    withdrawal: 'WithdrawalBatchActions'
    cryptoorder: 'CryptoOrderBatchActions'
    setting: 'SettingBatchActions'
    coinsetting: 'CoinSettingBatchActions'
    paymentmethod: 'PaymentMethodBatchActions'
    admin: 'AdminBatchActions'
    referralsetting: 'ReferralSettingBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.user = UserBatchActions(self)
        self.balance = BalanceBatchActions(self)
        self.transaction = TransactionBatchActions(self)
        self.deposit = DepositBatchActions(self)
        self.withdrawal = WithdrawalBatchActions(self)
        self.cryptoorder = CryptoOrderBatchActions(self)
        self.setting = SettingBatchActions(self)
        self.coinsetting = CoinSettingBatchActions(self)
        self.paymentmethod = PaymentMethodBatchActions(self)
        self.admin = AdminBatchActions(self)
        self.referralsetting = ReferralSettingBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserCreateInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.User,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.User,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserUpdateInput,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.User,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWhereUniqueInput,
        data: types.UserUpsertInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserUpdateManyMutationInput,
        where: types.UserWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.User,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.User,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class BalanceBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.BalanceCreateInput,
        include: Optional[types.BalanceInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Balance,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.BalanceCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Balance,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.BalanceWhereUniqueInput,
        include: Optional[types.BalanceInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Balance,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.BalanceUpdateInput,
        where: types.BalanceWhereUniqueInput,
        include: Optional[types.BalanceInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Balance,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.BalanceWhereUniqueInput,
        data: types.BalanceUpsertInput,
        include: Optional[types.BalanceInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Balance,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.BalanceUpdateManyMutationInput,
        where: types.BalanceWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Balance,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.BalanceWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Balance,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class TransactionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.TransactionCreateInput,
        include: Optional[types.TransactionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Transaction,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.TransactionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Transaction,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.TransactionWhereUniqueInput,
        include: Optional[types.TransactionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Transaction,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.TransactionUpdateInput,
        where: types.TransactionWhereUniqueInput,
        include: Optional[types.TransactionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Transaction,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.TransactionWhereUniqueInput,
        data: types.TransactionUpsertInput,
        include: Optional[types.TransactionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Transaction,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.TransactionUpdateManyMutationInput,
        where: types.TransactionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Transaction,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.TransactionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Transaction,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class DepositBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.DepositCreateInput,
        include: Optional[types.DepositInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Deposit,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.DepositCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Deposit,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.DepositWhereUniqueInput,
        include: Optional[types.DepositInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Deposit,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.DepositUpdateInput,
        where: types.DepositWhereUniqueInput,
        include: Optional[types.DepositInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Deposit,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.DepositWhereUniqueInput,
        data: types.DepositUpsertInput,
        include: Optional[types.DepositInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Deposit,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.DepositUpdateManyMutationInput,
        where: types.DepositWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Deposit,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.DepositWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Deposit,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class WithdrawalBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.WithdrawalCreateInput,
        include: Optional[types.WithdrawalInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Withdrawal,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.WithdrawalCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Withdrawal,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.WithdrawalWhereUniqueInput,
        include: Optional[types.WithdrawalInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Withdrawal,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.WithdrawalUpdateInput,
        where: types.WithdrawalWhereUniqueInput,
        include: Optional[types.WithdrawalInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Withdrawal,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.WithdrawalWhereUniqueInput,
        data: types.WithdrawalUpsertInput,
        include: Optional[types.WithdrawalInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Withdrawal,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.WithdrawalUpdateManyMutationInput,
        where: types.WithdrawalWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Withdrawal,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.WithdrawalWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Withdrawal,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CryptoOrderBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CryptoOrderCreateInput,
        include: Optional[types.CryptoOrderInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.CryptoOrder,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CryptoOrderCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.CryptoOrder,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CryptoOrderWhereUniqueInput,
        include: Optional[types.CryptoOrderInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.CryptoOrder,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CryptoOrderUpdateInput,
        where: types.CryptoOrderWhereUniqueInput,
        include: Optional[types.CryptoOrderInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.CryptoOrder,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CryptoOrderWhereUniqueInput,
        data: types.CryptoOrderUpsertInput,
        include: Optional[types.CryptoOrderInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.CryptoOrder,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CryptoOrderUpdateManyMutationInput,
        where: types.CryptoOrderWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.CryptoOrder,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CryptoOrderWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.CryptoOrder,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class SettingBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.SettingCreateInput,
        include: Optional[types.SettingInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Setting,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.SettingCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Setting,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.SettingWhereUniqueInput,
        include: Optional[types.SettingInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Setting,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.SettingUpdateInput,
        where: types.SettingWhereUniqueInput,
        include: Optional[types.SettingInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Setting,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.SettingWhereUniqueInput,
        data: types.SettingUpsertInput,
        include: Optional[types.SettingInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Setting,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.SettingUpdateManyMutationInput,
        where: types.SettingWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Setting,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.SettingWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Setting,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CoinSettingBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CoinSettingCreateInput,
        include: Optional[types.CoinSettingInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.CoinSetting,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CoinSettingCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.CoinSetting,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CoinSettingWhereUniqueInput,
        include: Optional[types.CoinSettingInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.CoinSetting,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CoinSettingUpdateInput,
        where: types.CoinSettingWhereUniqueInput,
        include: Optional[types.CoinSettingInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.CoinSetting,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CoinSettingWhereUniqueInput,
        data: types.CoinSettingUpsertInput,
        include: Optional[types.CoinSettingInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.CoinSetting,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CoinSettingUpdateManyMutationInput,
        where: types.CoinSettingWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.CoinSetting,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CoinSettingWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.CoinSetting,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class PaymentMethodBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.PaymentMethodCreateInput,
        include: Optional[types.PaymentMethodInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.PaymentMethod,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.PaymentMethodCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.PaymentMethod,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.PaymentMethodWhereUniqueInput,
        include: Optional[types.PaymentMethodInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.PaymentMethod,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.PaymentMethodUpdateInput,
        where: types.PaymentMethodWhereUniqueInput,
        include: Optional[types.PaymentMethodInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.PaymentMethod,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.PaymentMethodWhereUniqueInput,
        data: types.PaymentMethodUpsertInput,
        include: Optional[types.PaymentMethodInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.PaymentMethod,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.PaymentMethodUpdateManyMutationInput,
        where: types.PaymentMethodWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.PaymentMethod,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.PaymentMethodWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.PaymentMethod,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AdminBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AdminCreateInput,
        include: Optional[types.AdminInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Admin,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AdminCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Admin,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AdminWhereUniqueInput,
        include: Optional[types.AdminInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Admin,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AdminUpdateInput,
        where: types.AdminWhereUniqueInput,
        include: Optional[types.AdminInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Admin,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AdminWhereUniqueInput,
        data: types.AdminUpsertInput,
        include: Optional[types.AdminInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Admin,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AdminUpdateManyMutationInput,
        where: types.AdminWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Admin,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AdminWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Admin,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ReferralSettingBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ReferralSettingCreateInput,
        include: Optional[types.ReferralSettingInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ReferralSetting,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ReferralSettingCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ReferralSetting,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ReferralSettingWhereUniqueInput,
        include: Optional[types.ReferralSettingInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ReferralSetting,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ReferralSettingUpdateInput,
        where: types.ReferralSettingWhereUniqueInput,
        include: Optional[types.ReferralSettingInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ReferralSetting,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ReferralSettingWhereUniqueInput,
        data: types.ReferralSettingUpsertInput,
        include: Optional[types.ReferralSettingInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ReferralSetting,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ReferralSettingUpdateManyMutationInput,
        where: types.ReferralSettingWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ReferralSetting,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ReferralSettingWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ReferralSetting,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma