# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class UserStatus(StrEnum):
    PENDING = 'PENDING'
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'
    BANNED = 'BANNED'

class TransactionType(StrEnum):
    BUY = 'BUY'
    SELL = 'SELL'
    TOPUP = 'TOPUP'
    WITHDRAW = 'WITHDRAW'
    REFERRAL_BONUS = 'REFERRAL_BONUS'

class TransactionStatus(StrEnum):
    PENDING = 'PENDING'
    PROCESSING = 'PROCESSING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'

class OrderType(StrEnum):
    BUY = 'BUY'
    SELL = 'SELL'

class OrderStatus(StrEnum):
    PENDING = 'PENDING'
    AWAITING_PAYMENT = 'AWAITING_PAYMENT'
    AWAITING_CRYPTO = 'AWAITING_CRYPTO'
    PROCESSING = 'PROCESSING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'
    EXPIRED = 'EXPIRED'

