from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Balance',
    'Transaction',
    'Deposit',
    'Withdrawal',
    'CryptoOrder',
    'Setting',
    'CoinSetting',
    'PaymentMethod',
    'Admin',
    'ReferralSetting',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'referredBy': 'User',
        'referrals': 'User',
        'balance': 'Balance',
        'transactions': 'Transaction',
        'deposits': 'Deposit',
        'withdrawals': 'Withdrawal',
        'cryptoOrders': 'CryptoOrder',
    },
    'Balance': {
        'user': 'User',
    },
    'Transaction': {
        'user': 'User',
    },
    'Deposit': {
        'user': 'User',
        'approvedBy': 'Admin',
    },
    'Withdrawal': {
        'user': 'User',
        'approvedBy': 'Admin',
    },
    'CryptoOrder': {
        'user': 'User',
    },
    'Setting': {
    },
    'CoinSetting': {
    },
    'PaymentMethod': {
    },
    'Admin': {
        'approvedDeposits': 'Deposit',
        'approvedWithdrawals': 'Withdrawal',
    },
    'ReferralSetting': {
    },
}

# fmt: on